package log_monitor;


/**
* log_monitor/FileModificationEvent.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from logs.idl
* Tuesday, October 27, 2009 9:37:08 PM BRST
*/

public final class FileModificationEvent implements org.omg.CORBA.portable.IDLEntity
{
  public String fileName = null;
  public String host = null;
  public String ip = null;
  public int date = (int)0;

  public FileModificationEvent ()
  {
  } // ctor

  public FileModificationEvent (String _fileName, String _host, String _ip, int _date)
  {
    fileName = _fileName;
    host = _host;
    ip = _ip;
    date = _date;
  } // ctor

} // class FileModificationEvent
