package log_monitor;

/**
* log_monitor/FileModificationEventHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from logs.idl
* Wednesday, October 28, 2009 3:12:44 AM BRST
*/

public final class FileModificationEventHolder implements org.omg.CORBA.portable.Streamable
{
  public log_monitor.FileModificationEvent value = null;

  public FileModificationEventHolder ()
  {
  }

  public FileModificationEventHolder (log_monitor.FileModificationEvent initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = log_monitor.FileModificationEventHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    log_monitor.FileModificationEventHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return log_monitor.FileModificationEventHelper.type ();
  }

}
