package log_monitor;


/**
* log_monitor/FileModificationEvent.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from logs.idl
* Sunday, November 8, 2009 6:21:06 PM BRST
*/

public final class FileModificationEvent implements org.omg.CORBA.portable.IDLEntity
{
  public String fileName = null;
  public String host = null;
  public String ip = null;
  public long date = (long)0;

  public FileModificationEvent ()
  {
  } // ctor

  public FileModificationEvent (String _fileName, String _host, String _ip, long _date)
  {
    fileName = _fileName;
    host = _host;
    ip = _ip;
    date = _date;
  } // ctor

} // class FileModificationEvent
