package log_monitor;


/**
* log_monitor/FileModificationEventSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from logs.idl
* Sunday, November 8, 2009 6:21:06 PM BRST
*/

public final class FileModificationEventSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public log_monitor.FileModificationEvent value[] = null;

  public FileModificationEventSeqHolder ()
  {
  }

  public FileModificationEventSeqHolder (log_monitor.FileModificationEvent[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = log_monitor.FileModificationEventSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    log_monitor.FileModificationEventSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return log_monitor.FileModificationEventSeqHelper.type ();
  }

}
