package log_monitor;


/**
* log_monitor/MonitorConfigurationHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from logs.idl
* Sunday, November 8, 2009 6:21:06 PM BRST
*/

abstract public class MonitorConfigurationHelper
{
  private static String  _id = "IDL:log_monitor/MonitorConfiguration:1.0";

  public static void insert (org.omg.CORBA.Any a, log_monitor.MonitorConfiguration that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static log_monitor.MonitorConfiguration extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (log_monitor.MonitorConfigurationHelper.id (), "MonitorConfiguration");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static log_monitor.MonitorConfiguration read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_MonitorConfigurationStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, log_monitor.MonitorConfiguration value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static log_monitor.MonitorConfiguration narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof log_monitor.MonitorConfiguration)
      return (log_monitor.MonitorConfiguration)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      log_monitor._MonitorConfigurationStub stub = new log_monitor._MonitorConfigurationStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static log_monitor.MonitorConfiguration unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof log_monitor.MonitorConfiguration)
      return (log_monitor.MonitorConfiguration)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      log_monitor._MonitorConfigurationStub stub = new log_monitor._MonitorConfigurationStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
