package log_monitor;


/**
* log_monitor/MonitorConfiguration.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from logs.idl
* Sunday, November 8, 2009 6:21:06 PM BRST
*/

public interface MonitorConfiguration extends MonitorConfigurationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MonitorConfiguration
