package log_monitor;


/**
* log_monitor/MonitorConfigurationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from logs.idl
* Sunday, November 8, 2009 6:21:06 PM BRST
*/

public interface MonitorConfigurationOperations 
{
  long getInterval ();
  void setInterval (long interval);
  void addFile (String file);
  String[] getMonitoringFiles ();
  String getHost ();
} // interface MonitorConfigurationOperations
