package log_monitor;


/**
* log_monitor/MonitorConfigurationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from logs.idl
* Tuesday, October 27, 2009 9:37:08 PM BRST
*/

public interface MonitorConfigurationOperations 
{
  void addFile (String file);
  String[] getMonitoringFiles ();
  String getHost ();
} // interface MonitorConfigurationOperations
