package log_monitor;


/**
* log_monitor/MonitorConfiguration.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from logs.idl
* Wednesday, October 28, 2009 3:12:44 AM BRST
*/

public interface MonitorConfiguration extends MonitorConfigurationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MonitorConfiguration
