package log_viewer;


/**
* log_viewer/MonitoringOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from logs.idl
* Sunday, November 8, 2009 6:21:06 PM BRST
*/

public interface MonitoringOperations 
{
  log_monitor.FileModificationEvent[] getModifications ();
  void clear ();
} // interface MonitoringOperations
