package log_viewer;


/**
* log_viewer/MonitoringOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from logs.idl
* Tuesday, October 27, 2009 9:37:08 PM BRST
*/

public interface MonitoringOperations 
{
  log_monitor.FileModificationEvent[] getModifications ();
  void clear ();
} // interface MonitoringOperations
