package log_viewer;


/**
* log_viewer/MonitoringOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from logs.idl
* Wednesday, October 28, 2009 3:16:59 AM BRST
*/

public interface MonitoringOperations 
{
  log_monitor.FileModificationEvent[] getModifications ();
  void clear ();
} // interface MonitoringOperations
