package log_viewer;


/**
* log_viewer/ViewAdministrationMonitoring.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from logs.idl
* Sunday, November 8, 2009 6:21:06 PM BRST
*/

public interface ViewAdministrationMonitoring extends ViewAdministrationMonitoringOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ViewAdministrationMonitoring
