package log_viewer;

/**
* log_viewer/ViewAdministrationMonitoringHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from logs.idl
* Wednesday, October 28, 2009 3:16:59 AM BRST
*/

public final class ViewAdministrationMonitoringHolder implements org.omg.CORBA.portable.Streamable
{
  public log_viewer.ViewAdministrationMonitoring value = null;

  public ViewAdministrationMonitoringHolder ()
  {
  }

  public ViewAdministrationMonitoringHolder (log_viewer.ViewAdministrationMonitoring initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = log_viewer.ViewAdministrationMonitoringHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    log_viewer.ViewAdministrationMonitoringHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return log_viewer.ViewAdministrationMonitoringHelper.type ();
  }

}
