package log_viewer;


/**
* log_viewer/ViewAdministrationMonitoringOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from logs.idl
* Wednesday, October 28, 2009 3:12:44 AM BRST
*/

public interface ViewAdministrationMonitoringOperations 
{
  String[] getMonitoringFiles ();
} // interface ViewAdministrationMonitoringOperations
