package log_viewer;


/**
* log_viewer/ViewAdministrationMonitoringOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from logs.idl
* Sunday, November 8, 2009 6:21:06 PM BRST
*/

public interface ViewAdministrationMonitoringOperations 
{
  void pause ();
  void resume ();
  boolean isPaused ();
} // interface ViewAdministrationMonitoringOperations
