package event_service;


/**
* event_service/ChannelCollectionPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from events.idl
* Tuesday, October 27, 2009 9:23:50 PM BRST
*/

public class ChannelCollectionPOATie extends ChannelCollectionPOA
{

  // Constructors

  public ChannelCollectionPOATie ( event_service.ChannelCollectionOperations delegate ) {
      this._impl = delegate;
  }
  public ChannelCollectionPOATie ( event_service.ChannelCollectionOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public event_service.ChannelCollectionOperations _delegate() {
      return this._impl;
  }
  public void _delegate (event_service.ChannelCollectionOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public scs.core.IComponent getChannel (String name)
  {
    return _impl.getChannel(name);
  } // getChannel

  public event_service.ChannelDescr[] getAll ()
  {
    return _impl.getAll();
  } // getAll

  private event_service.ChannelCollectionOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class ChannelCollectionPOATie
