package event_service;


/**
* event_service/ChannelDescr.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from events.idl
* Tuesday, October 27, 2009 9:23:50 PM BRST
*/

public final class ChannelDescr implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public scs.core.IComponent channel = null;

  public ChannelDescr ()
  {
  } // ctor

  public ChannelDescr (String _name, scs.core.IComponent _channel)
  {
    name = _name;
    channel = _channel;
  } // ctor

} // class ChannelDescr
