package event_service;


/**
* event_service/ChannelDescrSeqHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from events.idl
* Tuesday, October 27, 2009 9:23:50 PM BRST
*/

abstract public class ChannelDescrSeqHelper
{
  private static String  _id = "IDL:event_service/ChannelDescrSeq:1.0";

  public static void insert (org.omg.CORBA.Any a, event_service.ChannelDescr[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static event_service.ChannelDescr[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = event_service.ChannelDescrHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (event_service.ChannelDescrSeqHelper.id (), "ChannelDescrSeq", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static event_service.ChannelDescr[] read (org.omg.CORBA.portable.InputStream istream)
  {
    event_service.ChannelDescr value[] = null;
    int _len0 = istream.read_long ();
    value = new event_service.ChannelDescr[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = event_service.ChannelDescrHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, event_service.ChannelDescr[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      event_service.ChannelDescrHelper.write (ostream, value[_i0]);
  }

}
