package event_service;


/**
* event_service/ChannelCollectionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from events.idl
* Tuesday, October 27, 2009 9:23:50 PM BRST
*/

public interface ChannelCollectionOperations 
{
  scs.core.IComponent getChannel (String name);
  event_service.ChannelDescr[] getAll ();
} // interface ChannelCollectionOperations
