package event_service;

/**
* event_service/ChannelCollectionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from events.idl
* Tuesday, October 27, 2009 9:23:50 PM BRST
*/

public final class ChannelCollectionHolder implements org.omg.CORBA.portable.Streamable
{
  public event_service.ChannelCollection value = null;

  public ChannelCollectionHolder ()
  {
  }

  public ChannelCollectionHolder (event_service.ChannelCollection initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = event_service.ChannelCollectionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    event_service.ChannelCollectionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return event_service.ChannelCollectionHelper.type ();
  }

}
