package event_service;


/**
* event_service/EventSinkOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from events.idl
* Tuesday, October 27, 2009 9:23:50 PM BRST
*/

public interface EventSinkOperations 
{
  void push (org.omg.CORBA.Any ev);
  void disconnect ();
} // interface EventSinkOperations
