package event_service;

/**
* event_service/NameAlreadyInUseHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from events.idl
* Tuesday, October 27, 2009 9:23:50 PM BRST
*/

public final class NameAlreadyInUseHolder implements org.omg.CORBA.portable.Streamable
{
  public event_service.NameAlreadyInUse value = null;

  public NameAlreadyInUseHolder ()
  {
  }

  public NameAlreadyInUseHolder (event_service.NameAlreadyInUse initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = event_service.NameAlreadyInUseHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    event_service.NameAlreadyInUseHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return event_service.NameAlreadyInUseHelper.type ();
  }

}
