#ifndef LOG_MONITOR_IDL
#define LOG_MONITOR_IDL

#include "events.idl"

module util {
	typedef sequence<string> StringSeq;
};

module log_monitor {
   
   interface MonitorConfiguration {
        long long getInterval();
        void setInterval(in long long interval);
	void addFile(in string file);
	util::StringSeq getMonitoringFiles();
	string getHost();
   };
   
   struct FileModificationEvent {
	string fileName;
	string host;
	string ip;
	long long date;
   };

   typedef sequence<log_monitor::FileModificationEvent> FileModificationEventSeq;

};

module log_viewer {

	interface ViewAdministrationMonitoring {
		util::StringSeq getMonitoringFiles();
	};

	interface Monitoring {
		log_monitor::FileModificationEventSeq getModifications();
		void clear();
	};

};

#endif
